### ISSUE TITLE
NPE after opening the zoom menu

### ISSUE THREAD

**Issue by OliverO2** [Salomon88/intellij-performance-toolbox-plugin#39]
Plugin version: 1.0.2

Steps to reproduce:
1. Open a GC log.
2. With the chart tab selected, open the zoom menu by clicking on the "plus" icon, hover over different zoom settings.
3. If that is not enough, select a zoom setting different from the active one. (If necessary, repeat.)
4. The icon "IDE Internal Error" will start flashing.

Stack trace:
```
java.lang.NullPointerException
	at org.performancetoolbox.intellij.plugin.gcviewer.actions.ToggleZoomAction.getScale(ToggleZoomAction.java:34)
	at org.performancetoolbox.intellij.plugin.gcviewer.actions.ToggleZoomAction.isSelected(ToggleZoomAction.java:24)
	at com.intellij.openapi.actionSystem.ToggleAction.update(ToggleAction.java:72)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$1(ActionUtil.java:170)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.updateActionItem(PopupFactoryImpl.java:259)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.lambda$new$1(PopupFactoryImpl.java:244)
	at java.desktop/javax.swing.JList.fireSelectionValueChanged(JList.java:1804)
	at java.desktop/javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1818)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:443)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:453)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:497)
	at com.intellij.ui.popup.list.ListPopupImpl$MyListSelectionModel.setSelectionInterval(ListPopupImpl.java:759)
	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2205)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseMotionListener.mouseMoved(ListPopupImpl.java:547)
	at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:338)
	at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:337)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6697)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3363)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4560)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)```

**Comment by Salomon88** [comment]
Hello! Please can you provide us screenshots? I've made all steps from yours description and can't reproduce it

**Comment by OliverO2** [comment]
Sure, here's a short screen recording at the end of which you'll see the flashing error icon and the error popup in the lower right corner:

https://user-images.githubusercontent.com/4660803/119126970-0206d500-ba34-11eb-871b-d82d4c28b5da.mp4

Version information:

IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-53-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 4
Registry: debugger.watches.in.variables=false, ide.tooltip.initialDelay=607
Non-Bundled Plugins: Performance Toolbox (1.0.2) [...]
Kotlin: 211-1.4.32-release-IJ7142.27
Current Desktop: ubuntu:GNOME

**Comment by Salomon88** [comment]
And one more I will ask you. Please attach gc.log file

**Comment by OliverO2** [comment]
Here it is: [gc.log](https://github.com/Salomon88/intellij-performance-toolbox-plugin/files/6522364/gc.log)

**Comment by OliverO2** [comment]
If the issue still does not reproduce in a different environment:

* The plugin still works after the NPE occurs.
* Given that this this line causes the problem: https://github.com/Salomon88/intellij-performance-toolbox-plugin/blob/b346d4325ca5777a3d613f65f8d465fe3dccf15d/src/main/java/org/performancetoolbox/intellij/plugin/gcviewer/actions/ToggleZoomAction.java#L34
* It seems that `rawScale` temporarily shows up as `null` here, as `getText()` may return `null`.
* Maybe `getScale()` could just return an invalid factor (say 0) whenever `rawScale` is null and `setSelected()` would just do nothing in this case?

**Comment by Salomon88** [comment]
> If the issue still does not reproduce in a different environment:
> 
>     * The plugin still works after the NPE occurs.
> 
>     * Given that this this line causes the problem: https://github.com/Salomon88/intellij-performance-toolbox-plugin/blob/b346d4325ca5777a3d613f65f8d465fe3dccf15d/src/main/java/org/performancetoolbox/intellij/plugin/gcviewer/actions/ToggleZoomAction.java#L34
> 
>     * It seems that `rawScale` temporarily shows up as `null` here, as `getText()` may return `null`.
> 
>     * Maybe `getScale()` could just return an invalid factor (say 0) whenever `rawScale` is null and `setSelected()` would just do nothing in this case?

Yours solution looks good, but give us sometime. We'll try to reproduce it locally

**Comment by Salomon88** [comment]
Please update plugin

**Comment by OliverO2** [comment]
Tested the update, works as expected. Thanks!
